# Generated by Django 4.1.13 on 2026-03-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmhouse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
